# Markdown and math settings
markdown: kramdown
kramdown:
  input: GFM          # GitHub Flavored Markdown
  math_engine: mathjax
  hard_wrap: false
  parse_block_html: true

# Theme settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme

# Site info
# title: "My Math Blog"
# author:
#   name: "Your Name"
# description: "A blog for math and programming"
# baseurl: ""          # leave empty for personal site
# url: "https://yourusername.github.io"

# Permalinks
permalink: /:year/:month/:day/:title/
