# Site settings
# title: "My Math Blog"
# email: "you@example.com"
# description: "A blog for math and programming"
# baseurl: ""      # leave empty for personal site
# url: "https://yourusername.github.io"  # change to your URL
# author:
#   name: "Your Name"
#   email: "you@example.com"

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll  # or any theme you like

# Kramdown & MathJax settings
kramdown:
  input: GFM          # GitHub Flavored Markdown
  math_engine: mathjax
  hard_wrap: false
  parse_block_html: true

# Permalinks
permalink: /:year/:month/:day/:title/

# Collections (optional)
collections:
  posts:
    output: true
